Interactive Multimedia : March 2014: FireProjectile Class Reference
FireProjectile Class Reference
Static Public Member Functions
static void SetMagicWand (bool wandCondition)
static bool PlayerHasWand ()
Public Attributes
Rigidbody projectilePrefab
const float FIRE_DELAY = 0.15f
Private Member Functions
void Update ()
void CheckFireKey ()
void CreateProjectile ()
Private Attributes
const float MIN_Y = -1
float projectileSpeed = 20f
float nextFireTime = 0f
Static Private Attributes
static bool hasMagicWand = false
Detailed Description
Provided by Dr Matt Smith
A class to fire projectiles, used with characters 'magic wand' Added a boolean to disable the wand action till WandCube is picked up Added two methods to control whether the player has the wand or not
Definition at line 11 of file FireProjectile.cs.
Member Function Documentation
void FireProjectile.CheckFireKey () [private]
Checks if player has wagic wand before firing
Definition at line 33 of file FireProjectile.cs.
References CreateProjectile(), FIRE_DELAY, hasMagicWand, and nextFireTime.
Referenced by Update().
{
                if(hasMagicWand){
                        if( Input.GetButton("Fire1")) {
                                CreateProjectile();
                                // enssure a delay before next projectile can be fired
                                nextFireTime = Time.time + FIRE_DELAY;
                        }
                }//end if-true
        }
void FireProjectile.CreateProjectile () [private]
Create clones of projectile as magic bullets from players wand
Definition at line 48 of file FireProjectile.cs.
References projectilePrefab, and projectileSpeed.
Referenced by CheckFireKey().
{
            Rigidbody projectile = (Rigidbody)Instantiate(projectilePrefab, transform.position, transform.rotation);
            // create and apply velocity
                Vector3 projectileVelocity = (projectileSpeed * Vector3.forward);
                // - need to use TransformDirection() so direciton is releative to current direction camera is facing
            projectile.velocity = transform.TransformDirection( projectileVelocity );
                Destroy( projectile.gameObject, 1.0f);
        }
static bool FireProjectile.PlayerHasWand () [static]
A method to find if the player has the magic wand
called from the GameGUI script
Definition at line 71 of file FireProjectile.cs.
References hasMagicWand.
Referenced by GameGUI.DrawWand().
{
                return hasMagicWand;
        }
static void FireProjectile.SetMagicWand (bool wandCondition) [static]
A method to give the player the magic wand
called from the WandCubeBehaviour script
Definition at line 63 of file FireProjectile.cs.
References hasMagicWand.
Referenced by WandCubeBehaviour.OnTriggerEnter(), and GameManager.Start().
{
                hasMagicWand = wandCondition;
        }
void FireProjectile.Update () [private]
Definition at line 24 of file FireProjectile.cs.
References CheckFireKey(), and nextFireTime.
                      {
                if( Time.time > nextFireTime )
                        CheckFireKey();
        }
Member Data Documentation
const float FireProjectile.FIRE_DELAY = 0.15f
shortest time between firing
Definition at line 18 of file FireProjectile.cs.
Referenced by CheckFireKey().
bool FireProjectile.hasMagicWand = false [static, private]
Definition at line 21 of file FireProjectile.cs.
Referenced by CheckFireKey(), PlayerHasWand(), and SetMagicWand().
const float FireProjectile.MIN_Y = -1 [private]
Definition at line 14 of file FireProjectile.cs.
float FireProjectile.nextFireTime = 0f [private]
Definition at line 19 of file FireProjectile.cs.
Referenced by CheckFireKey(), and Update().
Rigidbody FireProjectile.projectilePrefab
Definition at line 13 of file FireProjectile.cs.
Referenced by CreateProjectile().
float FireProjectile.projectileSpeed = 20f [private]
Definition at line 15 of file FireProjectile.cs.
Referenced by CreateProjectile().
The documentation for this class was generated from the following file:
C:/z_doxygen/src/FireProjectile.cs