Interactive Multimedia : March 2014: SpiderGunBehaviour Class Reference
SpiderGunBehaviour Class Reference
Static Public Member Functions
static void SetPlayerInRange ()
static void SetPlayerNotInRange ()
Public Attributes
Rigidbody projectilePrefab
const float FIRE_DELAY = 0.50f
Private Member Functions
void Update ()
void CheckForPlayer ()
void CreateProjectile ()
Private Attributes
const float MIN_Y = -1
float projectileSpeed = 15f
float nextFireTime = 0f
Static Private Attributes
static bool isPlayerInRange = false
Detailed Description
A script to control the behaviour of the spider gun
Which is the prefab attached to spiders which shoot at the player It is an adaptation of Dr Matt Smith's FireProjectile script
Definition at line 10 of file SpiderGunBehaviour.cs.
Member Function Documentation
void SpiderGunBehaviour.CheckForPlayer () [private]
Checks if player is in range before firing
Definition at line 33 of file SpiderGunBehaviour.cs.
References CreateProjectile(), FIRE_DELAY, isPlayerInRange, and nextFireTime.
Referenced by Update().
{
                if( isPlayerInRange ) {
                                CreateProjectile();
                                // enssure a delay before next projectile can be fired
                                nextFireTime = Time.time + FIRE_DELAY;
                        }
        }
void SpiderGunBehaviour.CreateProjectile () [private]
Create clones of projectile as magic bullets from players wand
Definition at line 44 of file SpiderGunBehaviour.cs.
References projectilePrefab, and projectileSpeed.
Referenced by CheckForPlayer().
{
                Rigidbody projectile = (Rigidbody)Instantiate(projectilePrefab, transform.position, transform.rotation);
                // create and apply velocity
                Vector3 projectileVelocity = (projectileSpeed * Vector3.forward);
                // - need to use TransformDirection() so direciton is releative to current direction camera is facing
                projectile.velocity = transform.TransformDirection( projectileVelocity );
                Destroy( projectile.gameObject, 1.0f);
        }
static void SpiderGunBehaviour.SetPlayerInRange () [static]
A method to confirm player in firing range
Definition at line 60 of file SpiderGunBehaviour.cs.
References isPlayerInRange.
Referenced by SpiderrangeBehaviour.OnTriggerEnter().
{
                isPlayerInRange = true;
        }
static void SpiderGunBehaviour.SetPlayerNotInRange () [static]
A method to confirm player not in firing range
Definition at line 67 of file SpiderGunBehaviour.cs.
References isPlayerInRange.
Referenced by SpiderrangeBehaviour.OnTriggerExit().
{
                isPlayerInRange = false;
        }
void SpiderGunBehaviour.Update () [private]
Definition at line 23 of file SpiderGunBehaviour.cs.
References CheckForPlayer(), and nextFireTime.
                      {
                if( Time.time > nextFireTime )
                        CheckForPlayer();
                //CheckPlayerInRange();
        }
Member Data Documentation
const float SpiderGunBehaviour.FIRE_DELAY = 0.50f
shortest time between firing
Definition at line 17 of file SpiderGunBehaviour.cs.
Referenced by CheckForPlayer().
bool SpiderGunBehaviour.isPlayerInRange = false [static, private]
Definition at line 20 of file SpiderGunBehaviour.cs.
Referenced by CheckForPlayer(), SetPlayerInRange(), and SetPlayerNotInRange().
const float SpiderGunBehaviour.MIN_Y = -1 [private]
Definition at line 13 of file SpiderGunBehaviour.cs.
float SpiderGunBehaviour.nextFireTime = 0f [private]
Definition at line 18 of file SpiderGunBehaviour.cs.
Referenced by CheckForPlayer(), and Update().
Rigidbody SpiderGunBehaviour.projectilePrefab
Definition at line 12 of file SpiderGunBehaviour.cs.
Referenced by CreateProjectile().
float SpiderGunBehaviour.projectileSpeed = 15f [private]
Definition at line 14 of file SpiderGunBehaviour.cs.
Referenced by CreateProjectile().
The documentation for this class was generated from the following file:
C:/z_doxygen/src/SpiderGunBehaviour.cs