Interactive Multimedia : March 2014: PlayerBehaviour Class Reference
PlayerBehaviour Class Reference
Public Member Functions
void OnTriggerEnter (Collider c)
Static Public Member Functions
static void DecreasePlayerLife ()
static void IncreasePlayerLife ()
static void IncreasePlayerLife (int lifeUp)
static int GetPlayerLife ()
Public Attributes
AudioClip gotWandSound
Static Public Attributes
static int playerLife = 10
Detailed Description
Methods to deal with player variables such as life, does he have the wand
Definition at line 8 of file PlayerBehaviour.cs.
Member Function Documentation
static void PlayerBehaviour.DecreasePlayerLife () [static]
Setter method to decrease the player life value
Definition at line 18 of file PlayerBehaviour.cs.
References playerLife.
Referenced by ToxicAreaBehaviour.OnTriggerEnter(), and SpiderBulletBehaviour.OnTriggerEnter().
{
                playerLife--;
        }
static int PlayerBehaviour.GetPlayerLife () [static]
Getter method for the player life value
Definition at line 46 of file PlayerBehaviour.cs.
References playerLife.
Referenced by GameGUI.CheckLevelOver(), and GameGUI.DrawLifeBar().
{
                return playerLife;
        }
static void PlayerBehaviour.IncreasePlayerLife () [static]
Setter method to increase the player life value
Definition at line 25 of file PlayerBehaviour.cs.
References playerLife.
Referenced by MushroomCircleBehaviour.Update().
{
                playerLife++;
                if (playerLife > 10) {
                        playerLife = 10;
                }
        }
static void PlayerBehaviour.IncreasePlayerLife (int lifeUp) [static]
Setter method to increase the player life value Takes a value in to increase life by, but will max out at 10
Definition at line 36 of file PlayerBehaviour.cs.
References playerLife.
{
                playerLife += lifeUp;
                if (playerLife > 10) {
                        playerLife = 10;
                }
        }
void PlayerBehaviour.OnTriggerEnter (Collider c)
Definition at line 50 of file PlayerBehaviour.cs.
References gotWandSound.
{
                string tag = c.tag;
                //Give player the magic wand
                if("WandCube" == tag){
                        audio.PlayOneShot (gotWandSound);
                }
        }//end OnTriggerEnter
Member Data Documentation
AudioClip PlayerBehaviour.gotWandSound
Definition at line 11 of file PlayerBehaviour.cs.
Referenced by OnTriggerEnter().
int PlayerBehaviour.playerLife = 10 [static]
Definition at line 10 of file PlayerBehaviour.cs.
Referenced by DecreasePlayerLife(), GetPlayerLife(), and IncreasePlayerLife().
The documentation for this class was generated from the following file:
C:/z_doxygen/src/PlayerBehaviour.cs