Interactive Multimedia : March 2014: GameGUI Class Reference
GameGUI Class Reference
Public Member Functions
void DrawWand (int yPositionIn)
Static Public Member Functions
static void DecreaseBarrelsLeft ()
static void SetBarrelsLeft (int barrelsIn)
static void SetFinalLevel (bool finalIn)
static void DecreasePipesLeft ()
Public Attributes
Texture2D greenTime
Texture2D redTime
Texture2D hourglass
Texture2D lifeHeart
Texture2D toxicBarrel
Texture2D magicWand
int LevelToLoad = 7
int GameOverLevel = 5
int GameWonLevel = 8
Font thisFont
GameObject nextLevelMessage
Static Public Attributes
static int playerLife = 10
Private Member Functions
void Start ()
void OnGUI ()
void DrawTimeBar ()
void DrawLifeBar ()
void CheckLevelOver ()
void CheckFinalOver ()
void DrawBarrelsLeft ()
Private Attributes
CountdownTimer myTimer
int width = (Screen.width / 20)
Static Private Attributes
static int barrelsLeft = 3
static int pipesLeft = 2
static bool finalLevel
Detailed Description
IMM Project April 2014 B00064428 Daragh Walshe Game GUI class to manage HUD displays
Time Remaining, Players health, Barrels remaining etc.
Definition at line 12 of file GameGUI.cs.
Member Function Documentation
void GameGUI.CheckFinalOver () [private]
Loop to check number factory outlet pipes left to win game
Definition at line 158 of file GameGUI.cs.
References GameWonLevel, and pipesLeft.
Referenced by CheckLevelOver().
        {
                if(pipesLeft == 0)
                        Application.LoadLevel(GameWonLevel);
        }
void GameGUI.CheckLevelOver () [private]
Performs two checks:
Has all barrels been destroyed, if so go to next level
Is the players life > 0, if not go to game over level
Definition at line 139 of file GameGUI.cs.
References barrelsLeft, CheckFinalOver(), finalLevel, GameOverLevel, PlayerBehaviour.GetPlayerLife(), and LevelToLoad.
Referenced by OnGUI().
        {
                if(barrelsLeft == 0 && !finalLevel){
                        //Instantiate(nextLevelMessage); //not working ??
                        Application.LoadLevel(LevelToLoad);
                }
                if(barrelsLeft == 0 && finalLevel){
                        CheckFinalOver();
                }
                if(PlayerBehaviour.GetPlayerLife() < 0){
                        Application.LoadLevel(GameOverLevel);
                }
        }
static void GameGUI.DecreaseBarrelsLeft () [static]
Method to decrease the number of barrels left this level
Definition at line 183 of file GameGUI.cs.
References barrelsLeft.
Referenced by CubeBehaviourScript.OnTriggerEnter(), BarrelBehaviour2.OnTriggerEnter(), and BarrelBehaviour.OnTriggerEnter().
{
                barrelsLeft--;
        }
static void GameGUI.DecreasePipesLeft () [static]
Method to decrease the number of factory pipes
Definition at line 204 of file GameGUI.cs.
References pipesLeft.
Referenced by FactoryPipeBehaviour.OnTriggerEnter().
{
                pipesLeft--;
        }
void GameGUI.DrawBarrelsLeft () [private]
Loop to check number of barrels left this level, and draw on HUD
Definition at line 168 of file GameGUI.cs.
References barrelsLeft, toxicBarrel, and width.
Referenced by OnGUI().
        {
                //GUI.Label (new Rect (0, 250, width, 40+(barrelsLeft*62)), "Barrels");
                GUI.Box (new Rect (0,250,61,40),"Barrels");
                int yPosition = 290;
                for (int i=0; i<barrelsLeft; i++) {
                        GUI.Label(new Rect(0,yPosition,width,62), toxicBarrel);
                        yPosition += 62;
                }
        }
void GameGUI.DrawLifeBar () [private]
Loop ten times and place either a red or green block in a vertical stack depending on proportion of time left.
Shown on LHS of the screen.
Definition at line 105 of file GameGUI.cs.
References PlayerBehaviour.GetPlayerLife(), greenTime, lifeHeart, playerLife, redTime, and width.
Referenced by OnGUI().
        {
                int playerLife = PlayerBehaviour.GetPlayerLife();
                int baseLife = 9;
                GUI.Label (new Rect (0,0,width,40), lifeHeart);
                //GUI.Box (new Rect (0,0,80,40), lifeHeart)
                //loop 10 times and check life left against baselife
                for (int i=0; i<10; i++) {
                        int yPosition = 40+(i*20);
                        if(baseLife < playerLife){
                                GUI.Label(new Rect(0,yPosition,width,20), greenTime);
                                baseLife -= 1;
                        }
                        else{
                                GUI.Label(new Rect(0,yPosition,width,20), redTime);
                                baseLife -= 1;
                        }
                }
        }
void GameGUI.DrawTimeBar () [private]
Loop ten times and place either a red or green block in a vertical array depending on proportion of time left. Displayed on RHS of screen.
Definition at line 58 of file GameGUI.cs.
References DrawWand(), CountdownTimer.GetProportionTimeRemaining(), greenTime, hourglass, myTimer, redTime, and width.
Referenced by OnGUI().
        {
                float proportionTimeRemaining = myTimer.GetProportionTimeRemaining();
                float baseTime = 0.9f;
                int xPosition = ((Screen.width/20)*19);//int xPosition = ((Screen.width/20)*19)+15;
                int yPosition = 0;
                GUI.Label (new Rect (xPosition+6,0,width,40), hourglass);
                for (int i=0; i<10; i++) {
                        //adjust y position each loop
                        yPosition = 40+(i*20);
                        //loop 10 times and check time left against basetime(0.9)
                        //and decrement basetime each loop by 0.1
                        if(baseTime < proportionTimeRemaining){
                                GUI.Label(new Rect(xPosition+6,yPosition,width,20), greenTime);
                                baseTime -= 0.1f;
                        }
                        else{
                                GUI.Label(new Rect(xPosition+6,yPosition,width,20), redTime);
                                //GUI.Label(new Rect(xPosition+6,yPosition,width,20), redTime);
                                baseTime -= 0.1f;
                        }
                }
                DrawWand (yPosition);
        }
void GameGUI.DrawWand (int yPositionIn)
Draw the wand on the HUD when player collects
Definition at line 91 of file GameGUI.cs.
References magicWand, FireProjectile.PlayerHasWand(), and width.
Referenced by DrawTimeBar().
{
                if (FireProjectile.PlayerHasWand ()) {
                        yPositionIn += 20;
                        int xPosition = ((Screen.width/20)*19);
                        GUI.Label (new Rect (xPosition+6,yPositionIn,width,50), magicWand);
                }
        }
void GameGUI.OnGUI () [private]
Definition at line 43 of file GameGUI.cs.
References CheckLevelOver(), DrawBarrelsLeft(), DrawLifeBar(), and DrawTimeBar().
        {
                //LHS GUI HUD
                DrawLifeBar ();
                DrawBarrelsLeft ();
                //RHS GUI HUD
                DrawTimeBar ();
                CheckLevelOver ();
        }
static void GameGUI.SetBarrelsLeft (int barrelsIn) [static]
Setter for the number of barrels left this level
Definition at line 190 of file GameGUI.cs.
References barrelsLeft.
Referenced by GameManager.Start().
{
                barrelsLeft = barrelsIn;
        }
static void GameGUI.SetFinalLevel (bool finalIn) [static]
Setter for if final level boolean
Definition at line 197 of file GameGUI.cs.
References finalLevel.
Referenced by GameManager.Start().
{
                finalLevel = finalIn;
        }
void GameGUI.Start () [private]
Definition at line 38 of file GameGUI.cs.
References myTimer.
        {
                myTimer = GetComponent<CountdownTimer>();
        }
Member Data Documentation
int GameGUI.barrelsLeft = 3 [static, private]
Definition at line 28 of file GameGUI.cs.
Referenced by CheckLevelOver(), DecreaseBarrelsLeft(), DrawBarrelsLeft(), and SetBarrelsLeft().
bool GameGUI.finalLevel [static, private]
Definition at line 30 of file GameGUI.cs.
Referenced by CheckLevelOver(), and SetFinalLevel().
int GameGUI.GameOverLevel = 5
Definition at line 24 of file GameGUI.cs.
Referenced by CheckLevelOver().
int GameGUI.GameWonLevel = 8
Definition at line 25 of file GameGUI.cs.
Referenced by CheckFinalOver().
Texture2D GameGUI.greenTime
Definition at line 14 of file GameGUI.cs.
Referenced by DrawLifeBar(), and DrawTimeBar().
Texture2D GameGUI.hourglass
Definition at line 16 of file GameGUI.cs.
Referenced by DrawTimeBar().
int GameGUI.LevelToLoad = 7
Definition at line 23 of file GameGUI.cs.
Referenced by CheckLevelOver().
Texture2D GameGUI.lifeHeart
Definition at line 17 of file GameGUI.cs.
Referenced by DrawLifeBar().
Texture2D GameGUI.magicWand
Definition at line 20 of file GameGUI.cs.
Referenced by DrawWand().
CountdownTimer GameGUI.myTimer [private]
Definition at line 33 of file GameGUI.cs.
Referenced by DrawTimeBar(), and Start().
GameObject GameGUI.nextLevelMessage
Check to see if all the Barrels are Destroyed, or if player is dead
Definition at line 131 of file GameGUI.cs.
int GameGUI.pipesLeft = 2 [static, private]
Definition at line 29 of file GameGUI.cs.
Referenced by CheckFinalOver(), and DecreasePipesLeft().
int GameGUI.playerLife = 10 [static]
Definition at line 31 of file GameGUI.cs.
Referenced by DrawLifeBar().
Texture2D GameGUI.redTime
Definition at line 15 of file GameGUI.cs.
Referenced by DrawLifeBar(), and DrawTimeBar().
Font GameGUI.thisFont
Definition at line 26 of file GameGUI.cs.
Texture2D GameGUI.toxicBarrel
Definition at line 19 of file GameGUI.cs.
Referenced by DrawBarrelsLeft().
int GameGUI.width = (Screen.width / 20) [private]
Definition at line 36 of file GameGUI.cs.
Referenced by DrawBarrelsLeft(), DrawLifeBar(), DrawTimeBar(), and DrawWand().
The documentation for this class was generated from the following file:
C:/z_doxygen/src/GameGUI.cs