Interactive Multimedia : March 2014: GameManager Class Reference
GameManager Class Reference
Public Attributes
int timeForLevel = 20
int gameOverLevelIndex = 5
int barrelsForLevel = 3
bool isFinalLevel = false
bool playerHasWand = false
Private Member Functions
void Start ()
void Update ()
Private Attributes
CountdownTimer myTimer
Detailed Description
A class to set various gameplay elements such as:
How many barrels to destroy on any given level, time for level etc
Definition at line 9 of file GameManager.cs.
Member Function Documentation
void GameManager.Start () [private]
Definition at line 18 of file GameManager.cs.
References barrelsForLevel, isFinalLevel, myTimer, playerHasWand, CountdownTimer.ResetTimer(), GameGUI.SetBarrelsLeft(), GameGUI.SetFinalLevel(), FireProjectile.SetMagicWand(), and timeForLevel.
        {
                myTimer = GetComponent<CountdownTimer>();
                myTimer.ResetTimer(timeForLevel);
                GameGUI.SetBarrelsLeft (barrelsForLevel);
                //print ("BARRELS FOR LEVEL" + barrelsForLevel);
                GameGUI.SetFinalLevel (isFinalLevel);
                FireProjectile.SetMagicWand (playerHasWand);
        }
void GameManager.Update () [private]
Check to see if player has run out of time
Definition at line 33 of file GameManager.cs.
References gameOverLevelIndex, CountdownTimer.GetSecondsRemaining(), and myTimer.
        {
                int secondsLeft = myTimer.GetSecondsRemaining();
                if(secondsLeft < 0)
                {
                        Application.LoadLevel(gameOverLevelIndex);
                }
        }
Member Data Documentation
int GameManager.barrelsForLevel = 3
Definition at line 14 of file GameManager.cs.
Referenced by Start().
int GameManager.gameOverLevelIndex = 5
Definition at line 13 of file GameManager.cs.
Referenced by Update().
bool GameManager.isFinalLevel = false
Definition at line 15 of file GameManager.cs.
Referenced by Start().
CountdownTimer GameManager.myTimer [private]
Definition at line 12 of file GameManager.cs.
Referenced by Start(), and Update().
bool GameManager.playerHasWand = false
Definition at line 16 of file GameManager.cs.
Referenced by Start().
int GameManager.timeForLevel = 20
Definition at line 11 of file GameManager.cs.
Referenced by Start().
The documentation for this class was generated from the following file:
C:/z_doxygen/src/GameManager.cs