Interactive Multimedia : March 2014: CountdownTimer Class Reference
CountdownTimer Class Reference
Public Member Functions
int GetTotalSeconds ()
void ResetTimer (int seconds)
int GetSecondsRemaining ()
float GetProportionTimeRemaining ()
Private Attributes
float countdownTimerStartTime
int countdownTimerDuration
Detailed Description
Dr. Matt Smith's countdown timer script
Called by OnGUI to check proportion of level-time left
Note: This is not my work
Definition at line 9 of file CountdownTimer.cs.
Member Function Documentation
float CountdownTimer.GetProportionTimeRemaining ()
Definition at line 34 of file CountdownTimer.cs.
References GetSecondsRemaining(), and GetTotalSeconds().
Referenced by GameGUI.DrawTimeBar().
        {
                float proportionLeft = (float)GetSecondsRemaining() / (float)GetTotalSeconds();
                return proportionLeft;
        }
int CountdownTimer.GetSecondsRemaining ()
Definition at line 27 of file CountdownTimer.cs.
References countdownTimerDuration, and countdownTimerStartTime.
Referenced by GetProportionTimeRemaining(), and GameManager.Update().
        {
                int elapsedSeconds = (int)(Time.time - countdownTimerStartTime);
                int secondsLeft = (countdownTimerDuration - elapsedSeconds);
                return secondsLeft;
        }
int CountdownTimer.GetTotalSeconds ()
Definition at line 16 of file CountdownTimer.cs.
References countdownTimerDuration.
Referenced by GetProportionTimeRemaining().
        {
                return countdownTimerDuration;
        }
void CountdownTimer.ResetTimer (int seconds)
Definition at line 21 of file CountdownTimer.cs.
References countdownTimerDuration, and countdownTimerStartTime.
Referenced by GameManager.Start().
        {
                countdownTimerStartTime = Time.time;
                countdownTimerDuration = seconds;
        }
Member Data Documentation
int CountdownTimer.countdownTimerDuration [private]
Definition at line 12 of file CountdownTimer.cs.
Referenced by GetSecondsRemaining(), GetTotalSeconds(), and ResetTimer().
float CountdownTimer.countdownTimerStartTime [private]
Definition at line 11 of file CountdownTimer.cs.
Referenced by GetSecondsRemaining(), and ResetTimer().
The documentation for this class was generated from the following file:
C:/z_doxygen/src/CountdownTimer.cs